name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: seanxuu
          filename: github-metrics.svg

          # 基础区块
          base: header, community

          # 1. 最近活动
          plugin_activity: yes
          plugin_activity_limit: 8
          plugin_activity_days: 30
          plugin_activity_filter: issue, pr, release, fork, review, ref/create

          # 2. 语言统计
          plugin_languages: yes
          plugin_languages_limit: 8

          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_types: commit, pull_request, issue
          plugin_notable_repositories: yes
          plugin_notable_filter: "stars:>500"
          plugin_notable_from: organization

